name: green_style
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.15
  introduction_screen: ^3.1.4
  http: ^0.13.5
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "./assets/icons/launcher.png"
  adaptive_icon_background: "#00bfa6"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
  - assets/icons/